security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\Utilisateur:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        # Admin firewall
        admin:
            pattern: ^/admin
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\AdminAuthenticator
            logout:
                path: admin_logout
                target: admin_login
                
        # Main firewall for regular users
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginAuthenticator
            entry_point: App\Security\LoginAuthenticator
            logout:
                path: app_logout
                target: app_login
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

    access_control:
        # Admin routes - login page is public, rest requires ROLE_ADMIN
        - { path: ^/admin/login$, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        
        # User routes - require ROLE_USER
        - { path: ^/home, roles: ROLE_USER }
        - { path: ^/boutique, roles: ROLE_USER }
        - { path: ^/subscription, roles: ROLE_USER }
        
        # Public routes
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/$, roles: PUBLIC_ACCESS }  # Only the exact root path is public
        - { path: ^/shop, roles: PUBLIC_ACCESS }  # Shop routes are public
        - { path: ^/preview, roles: PUBLIC_ACCESS }  # Preview route is public
        - { path: ^/, roles: ROLE_USER }  # All other paths require authentication

    # Role hierarchy - ROLE_ADMIN inherits ROLE_USER permissions
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

when@test:
    security:
        password_hashers:
            App\Entity\Utilisateur:
                algorithm: auto
                cost: 4
        providers:
            app_user_provider:
                entity:
                    class: App\Entity\Utilisateur
                    property: email
        firewalls:
            main:
                lazy: true
                provider: app_user_provider
                custom_authenticator: App\Security\LoginAuthenticator
                logout:
                    path: app_logout
                    target: app_login
