# config/packages/security.yaml
security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\Utilisateur:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginAuthenticator
            logout:
                path: app_logout
                target: app_login
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

    access_control:
        - { path: ^/home, roles: ROLE_USER }
        - { path: ^/login, roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            App\Entity\Utilisateur:
                algorithm: auto
                cost: 4 # Lower for faster tests

        providers:
            app_user_provider:
                entity:
                    class: App\Entity\Utilisateur
                    property: email

        firewalls:
            main:
                lazy: true
                provider: app_user_provider
                custom_authenticator: App\Security\LoginAuthenticator
                logout:
                    path: app_logout
                    target: app_login

parameters:
    stripe_public_key: 'pk_test_51RncyPC63BzOcHvjBpRR8vIjKbluWG2o7nRSJOKkfovWjDbHvuuSc1tQT2oIcqryRrZZp1KK6JMsTD2szzbnVZ3000YmQrmImZ' # Replace with your test publishable key
    stripe_secret_key: 'sk_test_51RncyPC63BzOcHvjmOwOEne4zahiZauIZbr4F597Je8pYCz36jisPZ4L6VdvkChz4vmaCh3CpYyh0UViqMN2UIo50049on836t'      # Replace with your test secret key

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Controller\SubscriptionController:
        arguments:
            $stripeSecretKey: '%sk_test_51RncyPC63BzOcHvjmOwOEne4zahiZauIZbr4F597Je8pYCz36jisPZ4L6VdvkChz4vmaCh3CpYyh0UViqMN2UIo50049on836t%'